[package]
name = "fixed_typemap_macros"
version = "0.1.0"
edition = "2021"
license = "Unlicense"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.10"
syn = { version = "1.0.82", features = ["default", "extra-traits"] }
